version: '3.1'

services:
  db:
    container_name: mariadb
    restart: always
    image: mariadb
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - db-base:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
  api:
    container_name: api
    build: ./../api
    ports:
      - "${SPRING_PORT}:6379"
    depends_on:
      - db
      - phpmyadmin
      - redis
volumes:
  db-base:
  cache:
